import os
from dotenv import load_dotenv
load_dotenv()

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")

OSU_CLIENT_ID = os.getenv("OSU_CLIENT_ID")
OSU_CLIENT_SECRET = os.getenv("OSU_CLIENT_SECRET")

MAX_BEATMAP_CACHE = 100
MAX_DELETE_BATCH = 10

MAX_PARSED_MAP = 100

HTTP_MAX_RETRIES = 3
HTTP_RETRY_DELAY = 0.5